---
deployment:
  tasks:
    - export DEPLOYPATH=/home/diaawebc/public_html
    - /bin/cp -R api $DEPLOYPATH
    - /bin/cd $DEPLOYPATH/api
    - @/usr/local/bin/composer install --optimize-autoloader --no-dev
    - @/usr/local/bin/php artisan migrate --force
    - @/usr/local/bin/php artisan config:cache
    - @/usr/local/bin/php artisan route:cache
    - @/usr/local/bin/php artisan view:cache
