---
deployment:
  tasks:
    - export DEPLOYPATH=/home/diaawebc/public_html
    - export APIPATH=/home/diaawebc/public_html/api
    - export ARTISANPATH=/home/diaawebc/public_html/api/artisan
    - /bin/cp -R api $DEPLOYPATH
    - /bin/ls -d /opt/cpanel/*
    - /bin/ls -d /opt/cpanel/ea-php82/root/*
    - /bin/ls -d /usr/local/*
    - /bin/ls -d /usr/local/bin/*
    - /opt/cpanel/ea-php82/root/composer/bin/composer install --working-dir=$APIPATH --optimize-autoloader --no-dev
    - /usr/local/bin/php $ARTISANPATH migrate --force
    - /usr/local/bin/php $ARTISANPATH config:cache
    - /usr/local/bin/php $ARTISANPATH route:cache
    - /usr/local/bin/php $ARTISANPATH view:cache
